# REQUIRED. Your registered app must have a secret set. The secret is used to
# verify that webhooks are sent by github and not someone else on the internet.
# github_webhook_secret: ""

# REQUIRED. The ID of the github app
# github_app_id: 12345

# REQUIRED. The private key for the app, including line breaks.
# github_app_private_key: |
#   -----BEGIN RSA PRIVATE KEY-----
#   nice long key
#   -----END RSA PRIVATE KEY-----

# REQUIRED. Specify the type of build. Options are:
#   - docker: run in an ephemeral docker container
# build_type: docker

# The port on which to listen
# port: 3000

# The address on which to listen
# bind: "0.0.0.0"

# Configure destination channel and credentials for the snap in each repo
# repos:
#   repo_owner/repo_name:
#     # Snaps will be released to the hotfix channel <channel>/pr-<number>
#     channel: edge
#
#     # REQUIRED: Snapcraft login token. Generate this with:
#     # $ snapcraft export-login \
#     #             --snaps=<snap-name> \
#     #             --channels=<channel> \
#     #             --acls=package_push,package_release -
#     token: ""
